image: Visual Studio 2017

platform:
  - x86
  - x64

configuration: Release

cache:
  - C:\Tools\vcpkg\installed

install:
  - pushd C:\Tools\vcpkg && (git pull --quiet & popd)
  - vcpkg install cgal:%platform%-windows-static

build_script:
  - cd natural_neighbor && mkdir build && cd build
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %platform%
  - cmake .. -DCMAKE_BUILD_TYPE=%configuration% -G Ninja -DCMAKE_MAKE_PROGRAM="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.exe" -DCMAKE_TOOLCHAIN_FILE="C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=%platform%-windows-static
  - cmake --build .

after_build:
  - ps: |
      $stata_platform = switch ($Env:platform) {
          'x86' { 'WIN32' }
          'x64' { 'WIN64' }
      }
      Push-AppveyorArtifact spipolate_natural_neighbor.plugin -FileName spipolate_natural_neighbor.${stata_platform}.plugin

deploy:
  - provider: GitHub
    auth_token:
      secure: uAFSB7zZiQg/2xGQ2ln0Y9zthx1JPNb9rKeIJUFonpiZaDUG6T7TjoJacxg3ADgB
    artifact: /.*/
    draft: true
    on:
      APPVEYOR_REPO_TAG: true
